### PR TITLE
Feature/jonah/error styles

### PR DESCRIPTION
**Pull request by jopfre**

### CODE REVIEW

**Comment by jopfre** [comment]
this has the landing page and geo icon changes in it too, because i branched off that branch. what is best practice in this case?

**Comment by herecomesjaycee** [comment]
Normally you'd set the PR to merge to the branch you branched off on, but right now it's not a problem

**Review by herecomesjaycee — APPROVED** [review]
All looks good to me, geo is looking great.

**Comment by jopfre** [comment]
> Normally you'd set the PR to merge to the branch you branched off on, but right now it's not a problem

Ah ok that makes sense, will remember that in future.

**Pull request merged**
